# Compila librito LaTeX

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]
    branches: [ master ]
    tags:
      - 'v*' # pushush events to matching v*, i.e. v1.0, v20.15.10


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: LaTeX compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        # The root LaTeX file to be compiled
        root_file: Tao.tex
        # The working directory for the latex compiler to be invoked
        # working_directory: # optional
        # LaTeX engine to be used
        compiler: latexmk 
        # optional, default is latexmk
        # Extra arguments to be passed to the latex compiler
        # args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
        # Install extra packages by apt-get
        # extra_system_packages: # optional
    - name: Create Release
      id: create_release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Tao.pdf"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
